language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: sentialx@gmail.com
  api_key:
    secure: DRKzw5F9dSoi8FFSnyHhVLF1oKDTAdX1YYRySu4zpnb+AToowM6KXjoOPNhnommrxikfcLyqlRXWMfyX4YATevEKiyLAkgwiYsXvg3DruP5kETy94GQYCM8CuxCjXpUdnLIEbaFOKN2nciiYiKMJgxo5ZrTmTOWA2onblGdeYbvkvxIOmx0xMPECnQWiLunGHK4Rr9nVQpcYkKS+pQsq9hmVbSFp9DP0MhypZX5BT8h3Voscxl2rpsC7uFxMIcXUvOIRwkxitpUPHDbYdC9JA5zV22tdy4WTNlHT2MT87CaqJCWTQvvbc2Ztl1OYPITUjkROO4NIEpYP0K/MGlnxTWTFIHjG4cvVe9dngoyH3U/7CMUUSxpg2K2Kcx9DhM9p9OqPKSOQFD9DM9gjRvaFKejWWqHOJIeik8LzHLVcCusXEtQjWtW9Neh2SAakLqme5/1C+ZsWkbaBWHnf4Hbzj5F+JCIE8oqpIt4UrjLRzsvJgoZ3gwsu6oja768wdGiHCrsaY3TBRsqzp9Vk9QhZ21RqS9TukNi37BAYg3u+wLrNXaazc8f/v2UOecnqMCSItfHTF+gkX//UunDZF0pWA1WSsK0w5ZcKmUTdlCKdXwsRgdOq3HrUnVITcfg66SPY7K40S4KqGe3gFRnqYlbKtjnCqxzfFcSREnNKAy1+Svg=
  on:
    repo: Sential/easy-vm
