language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: sentialx@gmail.com
  api_key:
    secure: A1QmsKjp0K4OyAqErcIbU/9LKDkJ4wZXZz5gLh3j9/++qjPKCK5jh7mkASnQNzZLEF9E2K1FV5RYAVAShJrXurg6OjJoQHnvj4nIGC7JhXp7y7JOcReTIUpgbo5W0dEqxzxutgFfL4jFh+sIJBqN1gKLpXPTAZF1XsRM2/cuTx7iayXQ6tiIxnXLv7ypiQTd4Y80JE3dlcCODYIENE9kEjBzcMX5NxC4SuxlL8C5c8ApSXGl2/eAADbi1sTnJXWk141zbwTUQpfz02NU9mOn6FNceGTtYr9UNDzqm9YaXxL5nIcyxAXW8LEy8XcCNVZ8s3uaDQ2BrFOXZPvByRBc2fepHPlHpSgtWTBmWRSQUdjIvIQlNo1KLt/MECQa+tagkAwAd5RiFgiU1TGa6rLZvu7hfGxCRsmfu9P6gq6gvaCX0kYt6CE2h49SaTwgQrya7Bi1NEsCVLJNWqswvpfICVbR4uy/YbDkelW6iLiQ0CsXwZrAPLmZcZsjvhZxtu/GokF5erIdUFFpTrprmS84OPsF8JQLXH7pBFbZkPOtlVZJMZveZZ+dQvpr7sd31OQ5EYDwTss282LOIilLtNhhCM6uINZ6m/xrLZEXyqv62A0cemxwvNnCFRKC2gTDpjpUc6kkL1gJBLR5aEVCXZO3ej5S5mnqnmHAK6tElxH7QWw=
  on:
    repo: Sential/easy-vm
