language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: sentialx@gmail.com
  on:
    repo: Sential/easy-vm
  api-key:
  secure: SsjSIy71T/4h7oowx9dzEMA5gkf0y001EJvCYmAE4ooIGlg3CZpr/IzzjYJm5C4C3QcrMkrPwcX74vUumrH64Ke+HSdeGQYDXuaEoDZCoPBVveOC2gp89W5891hi4YfFjZKo3WjYZwbRbE6iLvXsBAUTvJFMSlouR+q22gfNykXjtImkmyBDKqLKIPCgsAKWPIWY5KC4BE59YY7nPEnBq8OKmnwCPAixvpcJZzUAYBb/W9wtp3Q2hMt354TT3ImTn0B4v2nAiTjKDz/0a/xC7hhjAyQF6M2lncnm+bvsDKHfqdZ1PG+dKn5wDgAjXKhuiXkUdRM+sz+jlpAxY8T04SYt1uIIFJ/j/Dad8PaIBLeWxwvzACdp7fm2ac4SKHi6J5xt3vFERyJ1B6beiNi4NgvjjN5B6NfjZVAn27ed7I5wNtMvi+MBlqT7LY18gXAljJ9wXlWCZf3QKxbJYjlIJET3qjv2HSy82TSnIh8g6mzM79KK92+62uzwaggPMSUcqOuRzUTs3pkTl/kXz2XbQEG8MBsTANUr4+3UqpAj7dVlxSVZMd+mmWDgP3OS8tyiFuNW4hQ0PKm4Nsz2FwMPf/F0mtkEEwEs7Q6MrSWc/UGiQqyUDgqagBlkmaqx1S9wLMMCKgTxRgX6gu4YdUtVDsvYCQW7CRuli2PgNHF9il0=
